version: '3'
services:
  frontend:
    image: "nginx:alpine"
    ports:
      - "80:80"
    network_mode: "host"
    volumes:
      - ./default.conf:/etc/nginx/conf.d/default.conf:ro
      - ..:/webapps/gohorse/frontend
  database:
    image: "postgres:alpine"
    ports:
      - "5432:5432"
    network_mode: "host"
    environment:
      POSTGRES_PASSWORD: "gohorse"
      POSTGRES_USER: "vaicavalo"
      POSTGRES_DB: "gohorse"
