<template>
<v-container fluid>
  <v-card>
    <v-container fluid>
      <v-layout row wrap>
        <v-flex xs12 sm6 lg4 xg3 v-if="loadEnumerators" v-for="register in enumerators" :key="register.name">
          <v-card style="height: 500px; margin: 20px 10px">
            <v-btn absolute dark fab top right small color='red' @click="create(register)" style="z-index: 1;">
              <v-icon>add</v-icon>
            </v-btn>
            <v-card-title primary-title>
              <v-spacer></v-spacer>
              <div>
                <h4 class="headline text-truncation mb-2">{{register.name}}</h4>
              </div>
            </v-card-title>
            <v-divider></v-divider>
            <v-flex style="height: 400px; overflow-y: scroll">
              <v-list v-for="item in register.enumerators" :key="item.id">
                <v-layout row>
                  <v-flex xs6 sm6 lg8 xg8>
                    <p style="padding: 10px 10px; margin-top:5px"> <strong>{{item.name}} </strong></p>
                  </v-flex>
                  <v-flex xs3 sm3 lg2 xg2 v-if="!item.autoGenerated">
                    <v-btn flat color="blue" block @click="edit(register, item)">
                      <v-icon>mode_edit</v-icon>
                    </v-btn>
                  </v-flex>
                  <v-flex xs3 sm3 lg2 xg2 v-if="!item.autoGenerated">
                    <v-btn flat color="red" block @click="remove(register, item)">
                      <v-icon>delete</v-icon>
                    </v-btn>
                  </v-flex>
                </v-layout>
                <v-divider></v-divider>
              </v-list>
            </v-flex>
          </v-card>
        </v-flex>
      </v-layout>
      <v-layout row justify-center>
        <v-dialog v-model="dialog" max-width="400px">
          <v-card>
            <v-form ref="form" v-model="valid" @submit.prevent="save(registerForm, newName, item)" id="check-enum-form" lazy-validation>
              <v-card-title>
                <span class="headline">{{registerForm.name}}</span>
              </v-card-title>
              <v-card-text>
                <v-container grid-list-md>
                  <v-layout wrap>
                    <v-flex xs12>
                      <v-text-field id="nome" v-model="newName" :rules="nameRules" label="Nome" required></v-text-field>
                    </v-flex>
                  </v-layout>
                </v-container>
              </v-card-text>
              <v-card-actions>
                <v-spacer></v-spacer>
                <v-btn color="blue darken-1" flat @click.native="dismiss()">Fechar</v-btn>
                <v-btn type="submit" color="blue darken-1" flat :disabled='!formIsValid'>Salvar</v-btn>
              </v-card-actions>
            </v-form>
          </v-card>
        </v-dialog>
      </v-layout>
      <p class="grey--text pt-3" v-if="enumerators.length == 0"> Nenhum cadastro adicional encontrado </p>
    </v-container>
  </v-card>
</v-container>
</template>

<script>
import EnumeratorsService from './EnumeratorsService'

export default {
  data () {
    return {
      enumerators: [],
      registerForm: {},
      item: {},
      dialog: false,
      valid: true,
      newName: '',
      nameRules: [
        v => (v || '').length > 0 || 'Nome é obrigatorio',
        v => (v || '').length > 2 || 'Mínimo 3 caracteres'
      ]
    }
  },
  mounted () {
    const serialized = localStorage.getItem('authorization')
    if (!serialized || serialized === 'false') {
      this.$router.go('/login')
    }
    EnumeratorsService.getEnumerators((enumeratorsFound) => {
      this.enumerators = enumeratorsFound
    })
  },
  computed: {
    formIsValid () {
      return this.newName.length > 2
    },
    loadEnumerators () {
      EnumeratorsService.getEnumerators((enumeratorsFound) => {
        this.enumerators = enumeratorsFound
      })
      return true
    }
  },
  methods: {
    dismiss () {
      this.dialog = false
    },
    openForm (register, item) {
      this.$refs.form.reset()
      this.registerForm = register
      this.newName = ''
      this.valid = true
      if (item) {
        this.newName = item.name
      }
      this.item = item
      this.dialog = true
    },
    save (register, newName, item) {
      if (newName) {
        if (!item) {
          item = {
            name: '',
            kind: ''
          }
        }
        item.name = newName
        item.kind = register.name
        EnumeratorsService.saveEnumerator(item, () => {
          EnumeratorsService.getEnumerators((enumeratorsFound) => {
            this.enumerators = enumeratorsFound
          })
        })
        this.dialog = false
      }
    },
    edit (register, item) {
      this.registerForm = register
      this.openForm(register, item)
    },
    create (register) {
      this.registerForm = register
      this.openForm(register, null)
    },
    remove (register, item) {
      this.$swal({
        title: 'Você deseja deletar ?',
        text: 'Esta operação não pode ser desfeita',
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Sim, eu quero deletar!',
        cancelButtonText: 'Não'
      }).then((result) => {
        if (result.value) {
          EnumeratorsService.removeEnumerator(item.id, () => {
            EnumeratorsService.getEnumerators((enumeratorsFound) => {
              this.enumerators = enumeratorsFound
            })
          })
        }
      })
    }
  }
}
</script>
