<template>
<v-container fluid>
  <v-card>
    <v-container fluid>
      <v-layout row wrap>
        <v-flex xs12 sm6 lg4 xg3 v-if="loadEnumerators" v-for="register in enumerators" :key="register.name">
          <v-card style="height: 500px; margin: 20px 10px">
            <v-btn absolute dark fab top right small color='red' @click="create(register)" style="z-index: 1;">
              <v-icon>add</v-icon>
            </v-btn>
            <v-layout row justify-center>
              <v-dialog v-model="dialog" max-width="400px">
                <v-card>
                  <v-form v-model="valid" lazy-validation>
                    <v-card-title>
                      <span class="headline">{{registerForm.name}}</span>
                    </v-card-title>
                    <v-card-text>
                      <v-container grid-list-md>
                        <v-layout wrap>
                          <v-flex xs12>
                            <v-text-field id="nome" v-model="newName" :rules="nameRules" label="Nome" required></v-text-field>
                          </v-flex>
                        </v-layout>
                      </v-container>
                    </v-card-text>
                    <v-card-actions>
                      <v-spacer></v-spacer>
                      <v-btn color="blue darken-1" flat @click.native="dismiss()">Fechar</v-btn>
                      <v-btn color="blue darken-1" flat @click.native="save(registerForm, newName, item)">Salvar</v-btn>
                    </v-card-actions>
                  </v-form>
                </v-card>
              </v-dialog>
            </v-layout>
            <v-card-title primary-title>
              <v-spacer></v-spacer>
              <div>
                <h4 class="headline text-truncation mb-2">{{register.name}}</h4>
              </div>
            </v-card-title>
            <v-divider></v-divider>
            <v-flex style="height: 400px; overflow-y: scroll">
              <v-list v-for="item in register.enumerators" :key="item.id">
                <v-layout row>
                  <v-flex xs6 sm6 lg8 xg8>
                    <p style="padding: 10px 10px; margin-top:5px"> <strong>{{item.name}} </strong></p>
                  </v-flex>
                  <v-flex xs3 sm3 lg2 xg2 v-if="!item.autoGenerated">
                    <v-btn flat color="blue" block @click="edit(register, item)">
                      <v-icon>mode_edit</v-icon>
                    </v-btn>
                  </v-flex>
                  <v-flex xs3 sm3 lg2 xg2 v-if="!item.autoGenerated">
                    <v-btn flat color="red" block @click="remove(register, item)">
                      <v-icon>delete</v-icon>
                    </v-btn>
                  </v-flex>
                </v-layout>
                <v-divider></v-divider>
              </v-list>
            </v-flex>
          </v-card>
        </v-flex>
      </v-layout>
      <p class="grey--text pt-3" v-if="enumerators.length == 0"> Nenhum cadastro adicional encontrado </p>
    </v-container>
  </v-card>
</v-container>
</template>

<script>
  import EnumeratorsService from './EnumeratorsService'

export default {
  data () {
    return {
      enumerators: [],
      registerForm: {},
      item: {},
      dialog: false,
      valid: true,
      newName: '',
      nameRules: [
        v => !!v || 'Nome é obrigatorio'
      ]
    }
  },
  mounted () {
    EnumeratorsService.getEnumerators((enumeratorsFound) => {
      this.enumerators = enumeratorsFound
    })
  },
  computed: {
    loadEnumerators () {
      EnumeratorsService.getEnumerators((enumeratorsFound) => {
        this.enumerators = enumeratorsFound
      })
      return true
    }
  },
  methods: {
    dismiss () {
      this.dialog = false
    },
    computed: {
      loadEnumerators () {
        EnumeratorsService.getEnumerators((enumeratorsFound) => {
          this.enumerators = enumeratorsFound
        })
        return true
      }
      this.item = item
      this.dialog = true
    },
    methods: {
      dismiss () {
        this.dialog = false
      },
      openForm (register, item) {
        this.registerForm = register
        this.newName = ''
        this.valid = true
        if (item) {
          this.newName = item.name
        }
        this.item = item
        this.dialog = true
      },
      save (register, newName, item) {
        if (newName) {
          if (!item) {
            item = {
              name: '',
              kind: ''
            }
          }
          item.name = newName
          item.kind = register.name
          EnumeratorsService.saveEnumerator(item)
          this.$router.go(this.$route.path)
        }
        this.dismiss()
      },
      edit (register, item) {
        this.registerForm = register
        this.openForm(register, item)
      },
      create (register) {
        this.registerForm = register
        this.openForm(register, null)
      },
      remove (register, item) {
        this.$swal({
          title: 'Você deseja deletar ?',
          text: 'Esta operação não pode ser desfeita',
          type: 'warning',
          showCancelButton: true,
          confirmButtonText: 'Sim, eu quero deletar!',
          cancelButtonText: 'Não'
        }).then((result) => {
          if (result.value) {
            EnumeratorsService.removeEnumerator(item.id)
            this.$router.go(this.$route.path)
          }
        })
      }
      this.dismiss()
    },
    edit (register, item) {
      this.registerForm = register
      this.openForm(register, item)
    },
    create (register) {
      this.registerForm = register
      this.openForm(register, null)
    },
    remove (register, item) {
      this.$swal({
        title: 'Você deseja deletar ?',
        text: 'Esta operação não pode ser desfeita',
        type: 'warning',
        showCancelButton: true,
        confirmButtonText: 'Sim, eu quero deletar!',
        cancelButtonText: 'Não'
      }).then((result) => {
        if (result.value) {
          EnumeratorsService.removeEnumerator(item.id)
        }
      })
    }
  }
}
</script>
